### ISSUE TITLE
Exception on macOS (10.13.4)

### ISSUE THREAD

**Issue by arthwang** [JanWielemaker/inotify#1]
Hi Jan, thank you for your package.  This package works well on Debian 9 but raised an exception on macOS as follows:
?- pack_install(inotify).
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
% Pack `inotify' is already installed @0.9.1
true.

?- use_module(library(inotify)).
ERROR: /Users/laowang/lib/swipl/pack/inotify/prolog/inotify.pl:44:
	/Users/laowang/lib/swipl/pack/inotify/prolog/inotify.pl:44: Initialization goal raised exception:
	'$open_shared_object'/3: dlopen(inotify4pl, 1): image not found
ERROR: Exported procedure inotify:inotify_init/2 is not defined
true.

How to fix it?

**Comment by JanWielemaker** [comment]
Port it.  It encapsulates the Linux `inotify` API.  MacOS has (AFAIK) something similar, but not quite the same.  There are two options.  See whether you can emulate the required bits of `inotify` or wrap the MacOS alternative using the MacOS terminology and eventually write a Prolog library that provides a more high level and generic abstraction over the various implementation.

Would be nice to have ...

**Comment by arthwang** [comment]
Thank you Jan. But I don't have time to contribute for that.  It seems I'd try other solution to monitor file changes.

**Comment by JanWielemaker** [comment]
...  I heart people are using the command line tool started using `process_create` and then watch the output thereof.  Not sure there is public code.

**Comment by arthwang** [comment]
process_create seems not what i want.   I need to automatically reload page in browser after file change at swipl served backend during development and dynamical customization in maintenance. In debian i use your inotify and websocket to perform perfectly. But I also have to work on macOS often. 
I am reading the doc of fswatch, a cross-platform file change monitor lib, to see how much to do if 
 wrap it into swipl.

**Comment by JanWielemaker** [comment]
There is not that much wrong with using a process.  That just keeps running and you read the events from its standard output.   Using `libfswatch` would probably have been a better choice and it might be wise to migrate the current library.  I might do that at some point if nobody does, but it is unlikely to happen soon.

**Comment by arthwang** [comment]
Combination of process_create with fswatch works quite well now. Thank you very much :)
